### ISSUE TITLE
Investigate testing against various GCC/Clang Versions on Travis

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#3932]
In working on #3913, I discovered that we weren't ever actually properly testing against Clang, rather just the default version of gcc, which is 5.x on xenial. Unfortunately, it looks like trying to use the non-default gcc causes its own unique set of errors. Not sure what's going on here, but should be investigated.

gcc build: https://travis-ci.com/Submitty/Submitty/builds/116975113

Relevant Travis-CI changes for gcc:
```
    - &04-integration
      stage: Integration test
      language: cpp
      addons:
        postgresql: "9.5"
        apt:
          sources:
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
            - ubuntu-toolchain-r-test
          packages:
            - make
            - automake
            - cmake
            - dpkg-dev
            - libc6-dev
            - libseccomp2
            - seccomp
            - libseccomp-dev
            - valgrind
            - pkg-config
            - flex
            - bison
            - poppler-utils
            - libpcre3
            - libpcre3-dev
            - unzip
            - libboost-all-dev
      env: 
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install: 
        - source ${TRAVIS_BUILD_DIR}/.setup/travis/before_install.sh
        - eval "${MATRIX_EVAL}"
      install:
        - sudo apt-get install -qqy ${CXX}
        # - export LLVM_ARCHIVE_PATH=${HOME}/clang+llvm.tar.xz
        # - wget http://releases.llvm.org/${CLANG_VER}/clang+llvm-${CLANG_VER}-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O ${LLVM_ARCHIVE_PATH}
        # - mkdir ${HOME}/clang+llvm
        # - tar xf ${LLVM_ARCHIVE_PATH} -C ${HOME}/clang+llvm --strip-components 1
        # - export PATH=${HOME}/clang+llvm/bin:${PATH}
        # Create symlink so that it's in expected location for whitelist
        # - sudo ln -s $(which clang) /usr/bin/clang
        # - sudo ln -s $(which clang++) /usr/bin/clang++
        - pip3 install -U pip
        - pip3 install PyYAML
        - pip3 install python-dateutil
        - pip3 install paramiko
        - pip3 install psycopg2-binary
        - pip3 install sqlalchemy
        - pushd ${TRAVIS_BUILD_DIR}/python_submitty_utils
        - pip3 install .
        - popd
        - sudo bash .setup/travis/autograder.sh
        - psql -U postgres -c "CREATE ROLE submitty_dbuser WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'submitty_dbuser'"
        - PGPASSWORD=submitty_dbuser psql -d postgres -h localhost -U submitty_dbuser -c "CREATE DATABASE submitty"
        - sudo bash .setup/travis/setup.sh
        - sudo bash .setup/travis/setup_test_suite.sh
      script:
        - sudo python3 /usr/local/submitty/test_suite/integrationTests/run.py
    - <<: *04-integration
      env: 
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      # if: branch = master OR type = pull_request
    - <<: *04-integration
      env: 
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      # if: branch = master OR type = pull_request
    - <<: *04-integration
      env: 
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      # if: branch = master OR type = pull_request
```

Relevant changes for Clang:
Add after downloading and "installing" clang:
```
        - export CC=/usr/bin/clang
        - export CC_FOR_BUILD=/usr/bin/clang
        - export CXX=/usr/bin/clang++
        - export CXX_FOR_BUILD=/usr/bin/clang++
```
